version: "3"

services:
     
    wordpress:
        build: ./requirements/wordpress/
        image: wordpress
        restart: on-failure
        depends_on:
                - mariadb
        env_file: .env
        volumes:
            - wp_vol:/var/www/
        networks:
            - inception
    nginx:
        build: ./requirements/nginx/
        image: nginx
        restart: on-failure
        depends_on:
            - wordpress
        env_file: .env
        ports:
            - "443:443"
        volumes:
            - wp_vol:/var/www/
        networks:
            - inception

    mariadb:
        build: ./requirements/mariadb
        image: mariadb
        restart: on-failure
        env_file: .env
        volumes:
            - mdb_vol:/var/lib/mysql/
        networks:
            - inception
volumes:
    wp_vol:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/adconsta/data/wp_vol'

    mdb_vol:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/adconsta/data/mdb_vol'

networks:
    inception:
        driver: bridge
