version: "3.7"

services:
    nginx:
        build: ./nginx/
        image: mon_nginx
        #env_file: .env
        ports:
            - "443:443"
        volumes:
            - ./volume_1:${WP_VOL}
        networks:
            - inception

    wordpress:
        build: ./wordpress/
        image: mon_wp
        #env_file: .env
        volumes:
            - ./wp_vol:${WP_VOL}
        networks:
            - inception

    mariadb:
        build: ./mariadb
        image: mon_mdb
        volumes:
            - ./mdb_vol:${DB_VOL}
        #env_file: .env

networks:
    inception:
        driver: bridge


