version: "3.7"

services:
    nginx:
        build: ./nginx/
        image: mon_nginx
        env_file: .env
        ports:
            - "443:443"
        volumes:
            - wp_vol:/var/www/
        networks:
            - inception

    wordpress:
        build: ./wordpress/
        image: mon_wp
        env_file: .env
        volumes:
            - wp_vol:/var/www/
        networks:
            - inception

    mariadb:
        build: ./mariadb
        image: mon_mdb
        volumes:
            - mdb_vol:/var/lib/mysql/
volumes:
    wp_vol:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/calao/data/wp_vol'

    mdb_vol:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/calao/data/mdb_vol'

networks:
    inception:
        driver: bridge


