#!bin/bash

mkdir -p /var/www/wordpress
mv /usr/tmp_wp/*  /var/www/wordpress/

sed -i 's/WP_DB_NAME/$WP_DB_NAME/' /var/www/wordpress/wp-config.php
sed -i 's/WP_DB_USER/$WP_DB_USER/' /var/www/wordpress/wp-config.php
sed -i 's/WP_DB_PASSWORD/$WP_DB_PASSWORD/' /var/www/wordpress/wp-config.php
sed -i 's/localhost/$WP_DB_HOST/' /var/www/wordpress/wp-config.php
#sed -i 's/; daemonize = yes/ daemonize = no/' /etc/php/7.3/fpm/php-fpm.conf

exec /sbin/usr/php-fpm7.3 -F
