#!bin/bash

#mkdir -p /var/www/wordpress
#mv /usr/tmp_wp/*  /var/www/wordpress/

sed -i "s/WP_DB_NAME/$WP_DB_NAME/" /var/www/wordpress/wp-config.php
sed -i "s/WP_DB_USER/$WP_DB_USER/" /var/www/wordpress/wp-config.php
sed -i "s/WP_DB_PASSWORD/$WP_DB_PASSWORD/" /var/www/wordpress/wp-config.php
sed -i "s/WP_DB_HOST/$WP_DB_HOST/" /var/www/wordpress/wp-config.php

#sed -i 's/; daemonize = yes/ daemonize = no/' /etc/php/7.3/fpm/php-fpm.conf

#sed -i 's|listen = /run/php/php7.3-fpm.sock|listen = /run/php/php7.3-fpm.sock\nlisten = 9000|' etc/php/7.3/fpm/pool.d/www.conf

#mkdir -p run/php/

.//usr/sbin/php-fpm7.3 -F
