#!/bin/bash

#service mysql start
#sleep 3
#echo "FLUSH PRIVILEGES;" | mysql -u root --password=$MDB_ROOT_PASSWORD
#echo "CREATE DATABASE IF NOT EXISTS $WP_DB_NAME;" | mysql -u root --password=$MDB_ROOT_PASSWORD            
#echo "CREATE USER IF NOT EXISTS '$WP_DB_USER' IDENTIFIED BY '$WP_DB_PASSWORD';" | mysql -u root --password==$MDB_ROOT_PASSWORD
#echo "GRANT ALL ON $WP_DB_NAME.* TO '$WP_DB_USER'@'%';" | mysql -u root --password=$MDB_ROOT_PASSWORD
#echo "FLUSH PRIVILEGES;" | mysql -u root --password=$MDB_ROOT_PASSWORD
#mysqladmin -u root password $MDB_ROOT_PASSWORD
#service mysql stop

exec /usr/bin/mysqld_safe
