#!/bin/bash

service mysql start
database_exist=$(echo "SHOW DATABASES" | mysql -u root | grep "$WP_DB_NAME" | wc -l)
if [$database_exist = "0"]
then
	echo "CREATE DATABASE $WP_DB_NAME;" | mysql -u root                     
	echo "GRANT ALL ON $WP_DB_NAME.* TO '$WP_DB_USER'@'$WP_DB_HOST' IDENTIFIED BY			'$WP_DB_PASSWORD' WITH GRANT OPTION;" | mysql -u root
	echo "FLUSH PRIVILEGES;" | mysql -u root
	mysql $WP_DB_NAME -u root < /usr/mdb_tmp/starting_site.sql
fi

#if [volume_exist = 0]
#{
#	chown -R mysql:mysql /var/www/mariadb
#	cp -R -p /var/lib/mysql/* /var/www/mariadb
#	sed -i 's|datadir=/var/lib/mysql|datadir=/var/www/mariadb|' \
#			/etc/mysql/mariadb.conf.d/50-server.cnf
#	sed -i 's/\#port
#
#}
#cop
#echo "il existe ?" >> lol.txt /var/lib/mysql/

#echo "$WP_DB_NAME" 
#echo "$WP_DB_PASSWORD"

mysql -u root
