#!/bin/bash

service mysql start

echo "CREATE DATABASE IF NOT EXISTS $WP_DB_NAME;" | mysql -u root                     
echo "CREATE USER IF NOT EXISTS '$WP_DB_USER'@'$WP_DB_HOST' IDENTIFIED BY '$WP_DB_PASSWORD'" | mysql -u root
echo "GRANT ALL ON $WP_DB_NAME .* TO '$WP_DB_USER'@'%'" | mysql -u root"
echo "FLUSH PRIVILEGES;" | mysql -u root

#mysql $WP_DB_NAME -u root < /usr/mdb_tmp/starting_site.sql

#if [volume_exist = 0]
#{
#	chown -R mysql:mysql /var/www/mariadb
#	cp -R -p /var/lib/mysql/* /var/www/mariadb
#	sed -i 's|datadir=/var/lib/mysql|datadir=/var/www/mariadb|' \
#			/etc/mysql/mariadb.conf.d/50-server.cnf
#	sed -i 's/\#port
#
#}
#cop
#echo "il existe ?" >> lol.txt /var/lib/mysql/

#echo "$WP_DB_NAME" 
#echo "$WP_DB_PASSWORD"

mysql -u root
